- A-36 Tactical Grenade
- Accretion
- Adaptive Shield
- Adrenaline Rush
- Amp It Up
- Amplification Matrix
- Anchor
- Angelic Descent
- Annihilation
- Armor Pack
- Attack Speed
- Attack
- Augmented Fusion Driver
- Axe Recall
- Barbed Axe
- Barrage
- Barrier Field
- Barrier Projector
- Barrier Shield
- Berserker
- Biotic Field
- Biotic Grasp Alt Fire
- Biotic Grasp
- Biotic Grenade
- Biotic Launcher Alt Fire
- Biotic Launcher
- Biotic Orb
- Biotic Rifle
- Blink
- Blizzard
- Block (Nemesis Form)
- Bob
- Boosters
- Build Turret
- Burrow
- Caduceus Blaster
- Caduceus Staff
- Cage Fight
- Call Mech
- Captive Sun
- Cardiac Overdrive
- Carnage
- Catch
- Chain Hook
- Charge
- Clobber
- Coach Gun
- Coalescence
- Combat Roll
- Commanding Shout
- Concussion Mine
- Concussive Blast
- "Configuration: Artillery"
- "Configuration: Assault"
- "Configuration: Recon"
- "Configuration: Tank"
- Crossfade
- Cryo Freeze
- Cyber Agility
- Deadeye
- Death Blossom
- Defense Matrix
- Deflect
- Deploy Turret
- Dire Grenade
- Disruptor Shot
- Divine Assault
- Divine Power
- Dragonblade
- Dragonstrike
- Drill Dash
- Duplicate
- Dynamite
- Earthshatter
- Eject
- Emp
- Endothermic Blaster
- Energy Javelin
- Energy
- Exo Boots
- Experimental Barrier
- Explorers Resolve
- Fade
- Fan of Blades
- Fire Strike
- Flashbang
- Flight
- Flurry
- Focusing Beam
- Forge Hammer
- Fortify
- Frag Launcher
- Fusion Cannons
- Fusion Driver
- Glide
- Grappling Claw
- Grappling Hook
- Gravitic Flux
- Graviton Surge
- Guardian Angel
- Hack
- Halt
- Hand Cannon
- Healing Blossom
- Healing Boost
- Healing Ofuda
- Healing Pylon
- Health
- Heavy Pulse Rifle
- Helix Rockets
- Hellfire Desire
- Hellfire Shotguns
- Hover Jets
- Hyperspheres
- Ice Wall
- Icicle
- Immortality Field
- Incendiary Chaingun
- Infra Sight
- Inspire
- Ironclad
- Jagged Blade
- Javelin Spin
- Jet Dash
- Jump Jet
- Jump Pack
- Kinetic Grasp
- Kitsune Rush
- Kunai
- Life Grip
- Light Gun
- Lunge
- Machine Pistol
- Magnetic Grenade
- Melee Bump
- Meteor Strike
- Micro Missiles
- Minefield
- "Modifier: Death From Above"
- Molten Core
- Movement Speed
- Nano Boost
- Nemesis Form
- Nimble Feet
- Opportunist
- Orb of Destruction
- Orb of Discord
- Orb of Harmony
- Outburst
- Overclock
- Overload
- Overrun
- Particle Barrier
- Particle Cannon
- Peacekeeper
- Petal Platform
- Photon Barrier
- Photon Projector
- Pig Pen
- Piledriver
- Power Block
- Power Slide
- Primal Rage
- Projected Barrier
- Protection Suzu
- Pulse Bomb
- Pulse Pistols
- Pummel (Nemesis Form)
- Punch
- Quad Cannons
- Quick Melee
- Railgun Alt Fire
- Railgun
- Rally
- Rampage
- Ravenous Vortex
- Recall
- Reconfigure
- Regenerative Burst
- Rejuvenating Dash
- Repair Pack
- Resurrect
- Rip Tire
- Rising Uppercut
- Rivet Gun Alt Fire
- Rivet Gun
- Rocket Flail
- Rocket Hammer
- Rocket Launcher
- Rocket Punch
- Role Damage
- Role Support
- Role Tank
- Roll
- Rune of Disguise
- Scampy Stun
- Scatter Arrow
- Scattergun
- Scrap Gun
- Seismic Slam
- Self Destruct
- Self Repair
- Sentry Turret
- Shadow Step
- Shield Bash
- Shield Generator
- Shockwave
- Shuriken
- Sleep Dart
- Smart Excavator
- Snap Kick
- Snowball Blaster
- Solar Rifle
- Sonic Amplifier
- Sonic Arrow
- Soulbind
- Sound Barrier
- Soundwave
- Sprint
- Stealth
- Steel Trap
- Sticky Bombs
- Storm Arrows
- Storm Bow
- Strike
- Supercharger
- Swift Step
- Swift Strike
- Sympathetic Recovery
- Tactical Visor
- Take a Breather
- Tectonic Shock
- Teleporter
- Terra Surge
- Tesla Cannon
- Thaw
- The Best Defense
- The Reaping
- The Viper
- Thorn Volley
- Total Mayhem
- Transcendence
- Translocator
- Tree of Life
- Tri Shot
- Turbo Boost
- Ultimate Play
- Valkyrie
- Venom Mine
- Virus
- Volatile Chaingun
- Void Accelerator (Omnic Form)
- Void Barrier (Omnic Form)
- Wall Climb
- Wall Ride
- Wall Slam
- Whip Shot
- Whole Hog
- Widows Kiss
- Wraith Form
- Yeti Trap
