-
  name: D.va
  category: Tank
-
  name: Doomfist
  category: Tank
-
  name: Junker Queen
  category: Tank
  overwatch_2: true
-
  name: Mauga
  category: Tank
  overwatch_2: true
-
  name: Orisa
  category: Tank
-
  name: Ramattra
  category: Tank
  overwatch_2: true
-
  name: Reinhardt
  category: Tank
-
  name: Roadhog
  category: Tank
-
  name: Sigma
  category: Tank
-
  name: Winston
  category: Tank
-
  name: Wrecking Ball
  category: Tank
-
  name: Zarya
  category: Tank
-
  name: Ashe
  category: Damage
-
  name: Bastion
  category: Damage
-
  name: Cassidy
  category: Damage
-
  name: Echo
  category: Damage
-
  name: Genji
  category: Damage
-
  name: Hanzo
  category: Damage
-
  name: Junkrat
  category: Damage
-
  name: Mei
  category: Damage
-
  name: Pharah
  category: Damage
-
  name: Reaper
  category: Damage
-
  name: "Soldier: 76"
  category: Damage
-
  name: Sojourn
  category: Damage
  overwatch_2: true
-
  name: Sombra
  category: Damage
-
  name: Symmetra
  category: Damage
-
  name: Torbjörn
  category: Damage
-
  name: Tracer
  category: Damage
-
  name: Venture
  category: Damage
  overwatch_2: true
-
  name: Widowmaker
  category: Damage
-
  name: Ana
  category: Support
-
  name: Baptiste
  category: Support
-
  name: Brigitte
  category: Support
-
  name: Illari
  category: Support
  overwatch_2: true
-
  name: Juno
  category: Support
  overwatch_2: true
-
  name: Kiriko
  category: Support
  overwatch_2: true
-
  name: Lifeweaver
  category: Support
  overwatch_2: true
-
  name: Lúcio
  category: Support
-
  name: Mercy
  category: Support
-
  name: Moira
  category: Support
-
  name: Zenyatta
  category: Support
